docs(asyncpia-2.0.0): remove unknown key-value pair
asyncapi/spec pull request #523
Opened 2021-03-31 15:12 UTC by char0n

According to specification no `name` field exists within Parameter Object.

2021-06-14 08:40 UTC, magicmatatjahu approved these changes
LGTM! @derberg @fmvilas Could you also review?

2021-06-14 08:42 UTC, magicmatatjahu requested changes
I made a review too quickly 😅 Please also update branch.

2021-06-14 08:42 UTC, magicmatatjahu commented on spec/asyncapi.md
>    },
You should also remove it from https://github.com/asyncapi/spec/blame/0581e523d9e6fba1826ca4f529ee1bef94928df2/spec/asyncapi.md#L1487

2021-06-14 09:34 UTC, derberg commented
LGTM but as @magicmatatjahu pointed out, please remove this name field from both, json and yaml example. Also change PR title to `docs(spec)`

2021-06-16 08:47 UTC, char0n commented
All done.

2021-06-16 08:51 UTC, derberg approved these changes

2021-06-16 08:52 UTC, derberg commented
@magicmatatjahu once you approve and want to merge, make sure to put `[skip: ci]` in the commit details. You can leave it for me if you are scared 😄

2021-06-16 09:15 UTC, magicmatatjahu approved these changes
@derberg Please merge it 😅

2021-06-16 10:28 UTC, derberg commented
I already triggered 2 releases of 2.1 by accident so we can say I'm an expert in reverting bad decisions 😅

2021-06-16 10:28 UTC, merged

2021-06-16 10:29 UTC, derberg commented
no runs triggered https://github.com/asyncapi/spec/actions/workflows/release.yml
🚀