docs(spec): fix the type and decs of Operation.message field
asyncapi/spec pull request #603
Opened 2021-08-04 17:28 UTC by char0n

Refs #588

2021-08-04 18:25 UTC, fmvilas approved these changes

2021-09-15 05:54 UTC, fmvilas requested changes

2021-09-15 05:54 UTC, fmvilas commented on spec/asyncapi.md
> +<a name="operationObjectMessage"></a>message | [Message Object](#messageObject) &#124; [Reference Object](#referenceObject) &#124; Map["oneOf", [[Message Object](#messageObject) &#124; [Reference Obj
What about referring to the operation? It's not clear what is "channel" here.

```suggestion
<a name="operationObjectMessage"></a>message | [Message Object](#messageObject) &#124; [Reference Object](#referenceObject) &#124; Map["oneOf", [[Message Object](#messageObject) &#124; [Reference Object](#referenceObject)]] | A definition of the message that will be published or received by this operation. Map containing a single `oneOf` key is allowed here to specify multiple messages. However, **a message MUST be valid only against one of the message objects.**
```

2021-10-04 05:57 UTC, char0n commented
All requested changes here have been processed.

2021-12-10 08:44 UTC, char0n commented
Pinging here. Is there anything I can do to move this PR forward?

2021-12-21 17:24 UTC, derberg commented
@char0n it renders strange
![Screenshot 2021-12-21 at 18 24 20](https://user-images.githubusercontent.com/6995927/146972549-be9d455d-f48e-453f-bee2-cb01ac76f83a.png)

2021-12-21 19:28 UTC, char0n commented
@derberg can you be more specific what's strange about it? This type signature reflects exactly what the field allows in AsyncAPI 2.2.o spec. I agree it looks complex, but that's what spec currently allows.

Here a comment from @fmvilas that confirms it: https://github.com/asyncapi/spec/issues/588#issuecomment-886812393

2021-12-22 07:07 UTC, derberg commented
oh crap, you are right, immediately when I look at it, my brain tells me that formatting is broken, but you are rights, it is actually correct 😅 

@fmvilas you requested changes so you need to approve to get it merged

2022-01-03 18:06 UTC, fmvilas approved these changes

2022-01-03 18:07 UTC, fmvilas commented
/rtm

2022-01-03 18:08 UTC, merged