docs: adapting release process to new definition setup
asyncapi/spec pull request #659
Opened 2021-11-25 18:07 UTC by jonaslagoni

This PR adapts the release process documentation to follow the new definition setup in the [spec-json-schemas repository](https://github.com/asyncapi/spec-json-schemas).

2021-12-01 14:03 UTC, derberg commented
@jonaslagoni both PRs are draft, is it something you want me to look into now or wait?

2021-12-01 14:05 UTC, jonaslagoni commented
> @jonaslagoni both PRs are draft, is it something you want me to look into now or wait?

Forgot to take you off as a reviewer sorry!

We need to figure out https://github.com/asyncapi/spec-json-schemas/pull/128#issuecomment-981344308 before it can be finalized.

2022-03-14 12:14 UTC, jonaslagoni commented
I can't figure out if the link should point to https://github.com/asyncapi/spec-json-schemas/tree/next-major instead of master? 🧐

2022-03-14 12:46 UTC, fmvilas approved these changes
LGTM 👍

2022-03-14 12:48 UTC, fmvilas commented
I'd leave it pointing to master because we not only create new versions on majors.

2022-03-18 08:13 UTC, smoya commented
As the new changes in `spec-json-schemas` (splitting out definitions) will be used for the `2.4.0`, this branch could point now to the release branch `2022-04-release`.

2022-03-21 10:33 UTC, derberg commented
Hey folks, afaik split JSON Schema definitions are not released and are not in master, so should not be used in 2.4 and should not be mentioned in the release process document so far.

2022-03-21 10:33 UTC, derberg commented
Hey folks, afaik split JSON Schema definitions are not released and are not in master, so should not be used in 2.4 and should not be mentioned in the release process document so far.

2022-03-21 11:04 UTC, smoya commented
> Hey folks, afaik split JSON Schema definitions are not released and are not in master, so should not be used in 2.4 and should not be mentioned in the release process document for now, not on master.

They should totally be merged in `master` ASAP I would say. cc @jonaslagoni Why would we wait for releasing this?

2022-03-21 11:04 UTC, jonaslagoni commented
Related PR https://github.com/asyncapi/spec-json-schemas/pull/184

2022-03-23 14:28 UTC, jonaslagoni commented
> did you have some conversation somewhere about the definitions split that I'm not aware of? On PR that introduced it, I remember the goal was 3.0 spec release. This is why it was not released as `asyncapi/spec@3.0.0` but was exposed as a release candidate. And now all suddenly we need it ASAP for 2.4 🤷🏼

it was, however, the changes introduced for spec 3.0 is not a breaking change in itself, just another spec 🙂 And as I understood @smoya wanted the split definitions for spec 2.4 as it makes it much easier to contribute. That is the reason we are pushing for just releasing the feature.

2022-03-23 15:29 UTC, smoya commented
> did you have some conversation somewhere about the definitions split that I'm not aware of? On PR that introduced it, I remember the goal was 3.0 spec release. This is why it was not released as `asyncapi/spec@3.0.0` but was exposed as a release candidate. And now all suddenly we need it ASAP for 2.4 🤷🏼

Some of us realize during last Spec 3.0 meeting that this could be released earlier without having to wait since it has nothing to do with Spec 3.0. You can watch the video in https://youtu.be/GRfVx5bd9ag.
Of course, no decision was taken in the meeting, but I guess there is not a lot of decision to take i guess.

Why would we wait for realising this?

2022-03-23 22:19 UTC, dalelane approved these changes

2022-03-24 08:56 UTC, derberg commented
@smoya no need to wait, I was only surprised by a sudden change in approach and just wanted to understand where it is coming from 😄 I'm all with releasing it now. I'm actually always supportive of major releases in our libraries whenever there is a need, without being afraid of introducing breaking changes often, as long as it is needed from DX point of view.

2022-03-24 08:56 UTC, derberg approved these changes

2022-03-24 10:15 UTC, smoya approved these changes

2022-05-17 09:22 UTC, jonaslagoni commented
Alright, I have updated the PR and added links to the 3.0.0 schema changes as an example.

Is ready to be reviewed.

2022-05-17 20:35 UTC, fmvilas requested changes

2022-05-17 20:35 UTC, fmvilas commented on RELEASE_PROCESS.md
> +To create a new version, please read further in the repository under [Creating a new version](https://github.com/asyncapi/spec-json-schemas#creating-a-new-version),
```suggestion
To create a new version, please read [Creating a new version](https://github.com/asyncapi/spec-json-schemas#creating-a-new-version).
```

2022-05-22 12:44 UTC, dalelane approved these changes

2022-06-17 08:50 UTC, fmvilas approved these changes
👍

2022-06-17 09:33 UTC, fmvilas commented
/rtm

2022-06-17 09:33 UTC, merged

2023-01-31 10:28 UTC, derberg commented
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899