feat: make channels optional
asyncapi/spec pull request #682
Opened 2022-01-04 18:43 UTC by smoya

**Description**

Part of https://github.com/asyncapi/spec/issues/661.

This PR removes the `required` prefix from the `channels` field at root level of the document.

**Related issue(s)**
https://github.com/asyncapi/spec/issues/661

2022-01-18 13:02 UTC, magicmatatjahu approved these changes

2022-01-18 13:08 UTC, smoya commented
cc @derberg @fmvilas as you both are code owners.

2022-01-18 13:40 UTC, jonaslagoni commented
Is this not a breaking change? 🤔

2022-01-18 13:42 UTC, magicmatatjahu commented
@jonaslagoni 

> Is this not a breaking change? 🤔

If we switch optional to required then yes, but switching required -> optional won't break any AsyncAPI document.

2022-01-18 16:13 UTC, fmvilas commented
> Is this not a breaking change? 🤔

It will not be backward compatible but it will be forward compatible. I think we should also make it clear in the spec, that we aim for forward compatibility.

2022-01-18 16:18 UTC, fmvilas approved these changes
Looks good to me. Let's wait for @derberg.

2022-01-18 16:27 UTC, jonaslagoni commented
> Looks good to me. Let's wait for @derberg.

see https://github.com/asyncapi/spec/issues/688

2022-01-19 08:54 UTC, fmvilas requested changes
I thought twice about it and think this one is a breaking change and should be postponed to v3.

2022-01-19 09:50 UTC, dalelane commented
> I thought twice about it and think this one is a breaking change and should be postponed to v3.

I'll have a look to see if there is anything else that needs to be pulled out of 2.3 release branches

2022-01-19 10:24 UTC, smoya commented
As per https://github.com/asyncapi/spec-json-schemas/pull/146#issuecomment-1016290582, we won't include this change in `2.3.0` but rather in `3.0.0`.

2022-01-19 10:24 UTC, smoya commented
/dnm

2022-01-31 14:44 UTC, closed without merging