docs(release): specify new branch naming strategy
asyncapi/spec pull request #785
Opened 2022-05-05 15:48 UTC by smoya

Relates to https://github.com/asyncapi/spec/issues/734#issuecomment-1077455953

This PR changes the `RELEASE_PROCESS.md` to reflect the changes on the branch naming strategy for releasing; using `next-spec` and `next-major-spec` branches.
It also removes the step where the Release Coordinator should ask the Code Owners to create the release branch + the step where those should be added into `.releaserc` and/or `package.json` as they are not needed anymore.

2022-05-05 18:31 UTC, dalelane approved these changes
love how this made the process shorter :-)

2022-05-10 12:29 UTC, derberg submitted a review, later dismissed

2022-05-10 12:54 UTC, fmvilas requested changes
Just some minor (no pun intended) suggestion

2022-05-10 12:54 UTC, fmvilas commented on RELEASE_PROCESS.md
> +- `next-major-spec`: for releasing major versions. For example, `3.0.0`.
```suggestion
- `next-spec`: for releasing minor versions. For example, `2.3.0` to `2.4.0`.
- `next-major-spec`: for releasing major versions. For example, `2.4.0` to `3.0.0`.
```

2022-05-10 12:58 UTC, fmvilas approved these changes

2022-05-10 12:58 UTC, dalelane approved these changes
LGTM

2022-05-10 13:05 UTC, derberg approved these changes

2022-05-10 13:19 UTC, smoya commented
/rtm

2022-05-10 13:20 UTC, merged

2022-09-22 14:13 UTC, fmvilas commented
Forget about the last comment saying it was released in version 2.5.0-next-major-spec.1. I made a mistake and it created this version but it should actually be `3.0.0-next-major-spec.1`. There's a notice in the [release](https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-major-spec.1). Apologies for the noise.

2023-01-31 10:29 UTC, derberg commented
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899