docs: add bullets in keywords
asyncapi/spec pull request #790
Opened 2022-05-10 11:23 UTC by awantika10

**Related issue(s):**
Fixes #788 
---
@derberg please do let me know if any changes are required :)

2022-05-10 12:14 UTC, derberg approved these changes
lgtm

let's also wait for other reviewers

2022-05-13 20:14 UTC, dalelane approved these changes

2022-05-17 20:56 UTC, fmvilas requested changes
@awantika10 This paragraph has to be like this as per RFC 2119:

> Authors who follow these guidelines should incorporate this phrase near the beginning of their document:
>
>      The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
>      NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
>      "OPTIONAL" in this document are to be interpreted as described in
>      RFC 2119.

So I'm afraid I can't approve this PR. I'll leave a comment on the issue as well. Sorry for the confusion.

2022-09-16 06:34 UTC, fmvilas commented
Shall we close this PR then?

2022-09-16 07:58 UTC, closed without merging