add Pulsar bindings to the specification.
asyncapi/spec pull request #882
Opened 2022-12-09 12:19 UTC by VisualBean

---
title: "Add pulsar bindings and protocol to the specification"
---

---

**Related issue(s):**

The pulsar binding was finalized in the Bindings repository.
---

This PR adds the new pulsar binding objects, to the Server and Channel bindings list.
Along with adding "pulsar" to the protocol list.

2022-12-09 12:27 UTC, fmvilas requested changes
So far looks good to me but would you mind adding the operation and message bindings too? Even if we don't have any of those in the Pulsar binding yet but just so we have it here as a placeholder.

2022-12-09 14:20 UTC, VisualBean commented
> So far looks good to me but would you mind adding the operation and message bindings too? Even if we don't have any of those in the Pulsar binding yet but just so we have it here as a placeholder.

I have added these.

2022-12-09 14:22 UTC, fmvilas submitted a review, later dismissed
LGTM 👍

2022-12-19 16:20 UTC, char0n approved these changes
LGTM :+1:

2022-12-19 16:22 UTC, char0n commented
One small comment: do we want to update following section https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#protocol and add Google Pub/Sub and Pulsar there as well?

> Example protocols include, but are not limited to, AMQP, HTTP, JMS, Kafka, Anypoint MQ, MQTT, Solace, STOMP, Mercure, WebSocket, Google Cloud Pub/Sub, Pulsar.

2022-12-21 08:13 UTC, VisualBean commented
> One small comment: do we want to update following section https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#protocol and add Google Pub/Sub and Pulsar there as well?
> 
> > Example protocols include, but are not limited to, AMQP, HTTP, JMS, Kafka, Anypoint MQ, MQTT, Solace, STOMP, Mercure, WebSocket, Google Cloud Pub/Sub, Pulsar.

Done

2022-12-21 08:13 UTC, VisualBean commented on spec/asyncapi.md
> +A protocol is the mechanism (wireline protocol or API) by which [messages](#definitionsMessage) are exchanged between the application and the [channel](#definitionsChannel). Example protocols include
```suggestion
A protocol is the mechanism (wireline protocol or API) by which [messages](#definitionsMessage) are exchanged between the application and the [channel](#definitionsChannel). Example protocols include, but are not limited to, AMQP, HTTP, JMS, Kafka, Anypoint MQ, MQTT, Solace, STOMP, Mercure, WebSocket, Google Pub/Sub, Pulsar.  
```

2022-12-21 08:14 UTC, char0n approved these changes

2022-12-23 04:31 UTC, fmvilas submitted a review, later dismissed

2022-12-23 04:32 UTC, fmvilas commented
> One small comment: do we want to update following section https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#protocol and add Google Pub/Sub and Pulsar there as well?
> 
> > Example protocols include, but are not limited to, AMQP, HTTP, JMS, Kafka, Anypoint MQ, MQTT, Solace, STOMP, Mercure, WebSocket, Google Cloud Pub/Sub, Pulsar.

Just one small thing: this paragraph will be removed in v3.0.0. It's not intended to be an exhaustive list of protocols and very often I see folks getting confused thinking it actually is. Even though it says "not limited to" 😅

2022-12-23 10:47 UTC, VisualBean commented
Yeah, i completely agree, removing it, to lessen confusion makes sense. 
Also it's not really an actual protocols list per say, as some of these would use their own format anyway like `http` or `pulsar+ssl`.

2023-01-16 12:06 UTC, derberg commented
if this is planned for next release, target branch should not be `master` but `next-spec`

2023-01-16 12:09 UTC, derberg submitted a review, later dismissed
I set label to RFC 3 as it was already approved by 3 codeowners and binding before was also already approved and seen by others

also we have https://github.com/asyncapi/spec-json-schemas/pull/295

the only thing blocking is really the fact that these 2 PRs point to `master` branches and should to `next-spec`

2023-01-17 08:21 UTC, fmvilas commented
Changed the base branch but got conflicts now. @VisualBean I can't fix the conflicts for you because I don't have permission on your repo/branch. Please go ahead and fix them and that should be all.

2023-01-17 10:35 UTC, VisualBean commented
> Changed the base branch but got conflicts now. @VisualBean I can't fix the conflicts for you because I don't have permission on your repo/branch. Please go ahead and fix them and that should be all.

Awesome, thanks. I'll get them worked out

2023-01-18 08:08 UTC, derberg commented
@VisualBean due to update in `next-spec` branch there are some conflicts that you need to resolve, sorry

can you also change target in https://github.com/asyncapi/spec-json-schemas/pull/295 please, point to `next-spec` as well

2023-01-20 15:59 UTC, fmvilas approved these changes

2023-01-25 14:16 UTC, AceTheCreator commented
@fmvilas can you merge this PR?

2023-01-30 10:58 UTC, derberg approved these changes

2023-01-30 13:44 UTC, smoya approved these changes
LGTM!

2023-01-30 20:16 UTC, dalelane approved these changes

2023-01-31 09:26 UTC, derberg commented
/rtm

2023-01-31 09:26 UTC, merged

2023-01-31 10:26 UTC, derberg commented
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899